In [23]:
import numpy as np
import pandas as pd



In [4]:
df=pd.read_csv('hindi_english_parallel.csv')

In [5]:
df.head()

hindi  \
0    अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें   
1                    एक्सेर्साइसर पहुंचनीयता अन्वेषक   
2              निचले पटल के लिए डिफोल्ट प्लग-इन खाका   
3               ऊपरी पटल के लिए डिफोल्ट प्लग-इन खाका   
4  उन प्लग-इनों की सूची जिन्हें डिफोल्ट रूप से नि...   

                                          english  
0  Give your application an accessibility workout  
1               Accerciser Accessibility Explorer  
2  The default plugin layout for the bottom panel  
3     The default plugin layout for the top panel  
4  A list of plugins that are disabled by default

In [7]:
df.tail()

hindi  \
1561836  स्पष्टीकरण.–जहां इस उपधारा के अधीन हानि और लाभ...   
1561837  मैंने गौर किया है कि यह न केवल अपने महत्त्वपूर...   
1561838  उन्होंने मेरे समक्ष जो प्रदर्शन किया उसमें से ...   
1561839  खाद्य और जल सुरक्षा; पर्यावरण की दृष्टि से वहन...   
1561840                                                NaN   

                                                   english  
1561836  स्पष्टीकरण.–जहां इस उपधारा के अधीन हानि और लाभ...  
1561837  है। I note that this is a landmark meeting – n...  
1561838  है। In the presentations that they made before...  
1561839  ्त है। Issues such as food and water security;...  
1561840                                                NaN

In [6]:
len(df)

1561841

In [12]:
df[df.isnull().any(axis=1)]


hindi english
7695                                                   NaN   n / a
7838                                              कुछ नहीं     NaN
8273                                                   NaN   n / a
8416                                              कुछ नहीं     NaN
8880                                                   NaN   n / a
...                                                    ...     ...
1130790  हड़ताल करने, बहिष्कार करने, धरना करने, और अन्य...     NaN
1144190                                                NaN    NSDL
1144191                                                NaN  UTITSL
1158016                                                NaN     NaN
1561840                                                NaN     NaN

[6267 rows x 2 columns]

In [11]:
df.dtypes

hindi      object
english    object
dtype: object

In [13]:
df.dropna(inplace=True)

In [14]:
df[df.isnull().any(axis=1)]


Empty DataFrame
Columns: [hindi, english]
Index: []

In [15]:
df.tail()

hindi  \
1561835                    Members making oath/affirmation   
1561836  स्पष्टीकरण.–जहां इस उपधारा के अधीन हानि और लाभ...   
1561837  मैंने गौर किया है कि यह न केवल अपने महत्त्वपूर...   
1561838  उन्होंने मेरे समक्ष जो प्रदर्शन किया उसमें से ...   
1561839  खाद्य और जल सुरक्षा; पर्यावरण की दृष्टि से वहन...   

                                                   english  
1561835                शपथ लेने/प्रतिज्ञान करने वाले सदस्य  
1561836  स्पष्टीकरण.–जहां इस उपधारा के अधीन हानि और लाभ...  
1561837  है। I note that this is a landmark meeting – n...  
1561838  है। In the presentations that they made before...  
1561839  ्त है। Issues such as food and water security;...

In [22]:
df.head()

hindi  \
0    अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें   
1                    एक्सेर्साइसर पहुंचनीयता अन्वेषक   
2              निचले पटल के लिए डिफोल्ट प्लग-इन खाका   
3               ऊपरी पटल के लिए डिफोल्ट प्लग-इन खाका   
4  उन प्लग-इनों की सूची जिन्हें डिफोल्ट रूप से नि...   

                                          english  
0  Give your application an accessibility workout  
1               Accerciser Accessibility Explorer  
2  The default plugin layout for the bottom panel  
3     The default plugin layout for the top panel  
4  A list of plugins that are disabled by default

In [25]:
df=df.sample(n=100000)

In [4]:
df.reset_index(inplace=True)

In [24]:
df=pd.read_csv('sampledDataset.csv')

In [25]:
df.head()

Unnamed: 0                                              hindi  \
0           0  दो वर्ष की उम्र से स्थायी छेदक दांत पैदा होने ...   
1           1           किसी देश में बैंकिंग व्यवस्था का ढांचा।    
2           2  दो गवाह जो मारे गए उनमें से एक को तो खुलेआम, द...   
3           3       इस लड़ाई में सारे देश में एक चेतना जागी है।    
4           4  वह बोले हम तो गुनाहगारों (क़ौमे लूत) की तरफ भे...   

                                             english  
0  At the age of two years, the permanent incisor...  
1  The organisational set up of banking in a coun...  
2  Of the two that were killed, one was shot dead...  
3     The whole country has awakened during the war.  
4  They replied, "We have been sent to a sinful p...

In [26]:
df.columns

Index(['Unnamed: 0', 'hindi', 'english'], dtype='object')

In [27]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [28]:
df.iloc[99949,0]

'इसे पर्सेंटेज में बदलना चाहता हूँ '

In [179]:
df.to_csv('sampledDataset.csv')

In [29]:
df

hindi  \
0      दो वर्ष की उम्र से स्थायी छेदक दांत पैदा होने ...   
1               किसी देश में बैंकिंग व्यवस्था का ढांचा।    
2      दो गवाह जो मारे गए उनमें से एक को तो खुलेआम, द...   
3           इस लड़ाई में सारे देश में एक चेतना जागी है।    
4      वह बोले हम तो गुनाहगारों (क़ौमे लूत) की तरफ भे...   
...                                                  ...   
99995  और यदि तुम अल्लाह की नेमतों (कृपादानों) को गिन...   
99996  विश्वविद्यालयों की दो प्रतिष्ठित अंतरराष्ट्रीय...   
99997                                                 से   
99998                                     वह दुःस्वप्न!    
99999                                           कलश भाषा   

                                                 english  
0      At the age of two years, the permanent incisor...  
1      The organisational set up of banking in a coun...  
2      Of the two that were killed, one was shot dead...  
3         The whole country has awakened during the war.  
4      They replied, "We have been sent to a sinful p...  
...                                                  ...  
99995  And if you would count Allah 's favors, you wi...  
99996  In two reputed international rankings of unive...  
99997                                               From  
99998                                    That nightmare!  
99999                                    Kalash language  

[100000 rows x 2 columns]

In [30]:
df['english']=df['english'].str.lower()

In [31]:
df

hindi  \
0      दो वर्ष की उम्र से स्थायी छेदक दांत पैदा होने ...   
1               किसी देश में बैंकिंग व्यवस्था का ढांचा।    
2      दो गवाह जो मारे गए उनमें से एक को तो खुलेआम, द...   
3           इस लड़ाई में सारे देश में एक चेतना जागी है।    
4      वह बोले हम तो गुनाहगारों (क़ौमे लूत) की तरफ भे...   
...                                                  ...   
99995  और यदि तुम अल्लाह की नेमतों (कृपादानों) को गिन...   
99996  विश्वविद्यालयों की दो प्रतिष्ठित अंतरराष्ट्रीय...   
99997                                                 से   
99998                                     वह दुःस्वप्न!    
99999                                           कलश भाषा   

                                                 english  
0      at the age of two years, the permanent incisor...  
1      the organisational set up of banking in a coun...  
2      of the two that were killed, one was shot dead...  
3         the whole country has awakened during the war.  
4      they replied, "we have been sent to a sinful p...  
...                                                  ...  
99995  and if you would count allah 's favors, you wi...  
99996  in two reputed international rankings of unive...  
99997                                               from  
99998                                    that nightmare!  
99999                                    kalash language  

[100000 rows x 2 columns]

In [32]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=30000,oov_token="<OOV>")

In [33]:
tokenizer.fit_on_texts(df['english'])

In [188]:
import pickle
with open("Englishtokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

In [189]:
len(tokenizer.word_index)

58955

In [36]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'of': 3,
 'and': 4,
 'to': 5,
 'in': 6,
 'a': 7,
 'is': 8,
 'for': 9,
 'that': 10,
 'you': 11,
 'it': 12,
 'be': 13,
 'not': 14,
 'he': 15,
 'they': 16,
 'with': 17,
 'on': 18,
 'are': 19,
 'as': 20,
 'this': 21,
 'or': 22,
 'by': 23,
 'from': 24,
 'have': 25,
 'we': 26,
 'was': 27,
 'will': 28,
 'his': 29,
 'them': 30,
 'who': 31,
 'which': 32,
 'i': 33,
 'has': 34,
 'their': 35,
 'all': 36,
 'but': 37,
 'an': 38,
 'allah': 39,
 'at': 40,
 'your': 41,
 'one': 42,
 'if': 43,
 "'s": 44,
 'him': 45,
 'so': 46,
 'do': 47,
 'when': 48,
 'there': 49,
 'those': 50,
 'what': 51,
 'our': 52,
 'people': 53,
 'no': 54,
 'had': 55,
 'were': 56,
 'india': 57,
 'can': 58,
 'any': 59,
 'been': 60,
 'god': 61,
 'said': 62,
 'then': 63,
 'its': 64,
 's': 65,
 'shall': 66,
 'other': 67,
 'may': 68,
 'lord': 69,
 'also': 70,
 'only': 71,
 'such': 72,
 'my': 73,
 'would': 74,
 'day': 75,
 'these': 76,
 'time': 77,
 'say': 78,
 'out': 79,
 'some': 80,
 'new': 81,
 'up': 82,
 'made

In [35]:
numberOfEnglishWords=len(tokenizer.word_index)+1
numberOfEnglishWords

58956

In [37]:
sequences = tokenizer.texts_to_sequences(df['english'])

In [25]:
len(sequences)

100000

In [26]:
lengths = [len(seq) for seq in sequences]
import numpy as np
np.percentile(lengths, [90, 95, 99])


array([30., 39., 68.])

In [27]:
from tensorflow.keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding='post', value=0,maxlen=30, truncating='post',)

In [28]:
len(sequences[0])

30

In [38]:
df['hindi'] = df['hindi'].apply(
    lambda x: "<SOS> " + x + " <EOS>"
)


In [39]:
df['hindi'].iloc[0]

'<SOS> दो वर्ष की उम्र से स्थायी छेदक दांत पैदा होने शुरू हो जाते हैं।  <EOS>'

In [40]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer_hi = Tokenizer(
    num_words=30000,
    filters='',            # IMPORTANT: keep punctuation
    oov_token="<OOV>"
)

tokenizer_hi.fit_on_texts(df['hindi'])


In [195]:
import pickle
with open("Hinditokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer_hi, f)

In [196]:
numberOfHindiWords=len(tokenizer_hi.word_index)+1
numberOfHindiWords

108011

In [197]:
sequences_hi = tokenizer_hi.texts_to_sequences(df['hindi'])


In [51]:
tokenizer_hi.word_index

{'<OOV>': 1,
 '<sos>': 2,
 '<eos>': 3,
 'के': 4,
 'और': 5,
 'में': 6,
 'की': 7,
 'से': 8,
 'को': 9,
 'है': 10,
 'का': 11,
 'है।': 12,
 'कि': 13,
 'पर': 14,
 'एक': 15,
 'लिए': 16,
 'तो': 17,
 'जो': 18,
 'नहीं': 19,
 'भी': 20,
 'ही': 21,
 'ने': 22,
 'कर': 23,
 'यह': 24,
 'हो': 25,
 'वह': 26,
 'हैं': 27,
 'इस': 28,
 'किया': 29,
 'या': 30,
 'करने': 31,
 'है,': 32,
 'अपने': 33,
 'न': 34,
 'तुम': 35,
 'वे': 36,
 'कुछ': 37,
 'तथा': 38,
 'हैं।': 39,
 'किसी': 40,
 'कोई': 41,
 'हम': 42,
 'उनके': 43,
 'है.': 44,
 'साथ': 45,
 'लोग': 46,
 'लोगों': 47,
 'करते': 48,
 'जब': 49,
 'गया': 50,
 'द्वारा': 51,
 'रूप': 52,
 'उसके': 53,
 'ये': 54,
 'ख़ुदा': 55,
 'फिर': 56,
 'क्या': 57,
 'अल्लाह': 58,
 'तक': 59,
 'अपनी': 60,
 'उस': 61,
 'जा': 62,
 'दिया': 63,
 'जाता': 64,
 'मैं': 65,
 'भारत': 66,
 'उन्हें': 67,
 'उन': 68,
 'करता': 69,
 'उसे': 70,
 'करना': 71,
 'रहे': 72,
 'आप': 73,
 'होता': 74,
 'था': 75,
 'सकता': 76,
 'रहा': 77,
 'बहुत': 78,
 'हुए': 79,
 'करें': 80,
 'बात': 81,
 'पास': 82,
 'तुम्हारे': 83,
 '

In [35]:
lengths_hi = [len(seq) for seq in sequences_hi]
np.percentile(lengths_hi, [90, 95, 99])


array([35.  , 46.  , 79.01])

In [36]:
sequences_hi = pad_sequences(
    sequences_hi,
    maxlen=40,
    padding='post',
    truncating='post',
    value=0
)


In [37]:
len(sequences_hi[0])

40

In [38]:
decoder_input = sequences_hi[:, :-1]
decoder_target = sequences_hi[:, 1:]


In [39]:
decoder_input[0]

array([    2,    92,   148,     7,  1442,     8,  1106, 20976,  5022,
         177,   102,   324,    25,   204,    39,     3,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0])

In [40]:
decoder_target[0]

array([   92,   148,     7,  1442,     8,  1106, 20976,  5022,   177,
         102,   324,    25,   204,    39,     3,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0])

In [6]:
embedding_dim = 128
hidden_units = 256
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense
from tensorflow.keras.models import Model
def build_model():
    # Encoder
    encoder_input = Input(shape = (30, ))        #30 denotes length of each sentence after padding
    encoder_embedding = Embedding(30000, embedding_dim)(encoder_input)
    encoder_lstm = LSTM(hidden_units, return_state=True)
    encoder_outputs, encoder_hidden, encoder_cell = encoder_lstm(encoder_embedding)
    encoder_states = [encoder_hidden, encoder_cell]


    # Decoder
    decoder_input = Input(shape = (39, ))
    decoder_embedding = Embedding(30000, embedding_dim)(decoder_input)
    decoder_lstm = LSTM(hidden_units, return_sequences=True)
    decoder_output = decoder_lstm(decoder_embedding, initial_state = encoder_states)
    decoder_dense = Dense(30000, activation='softmax')
    decoder_output = decoder_dense(decoder_output)

    
    # final model
    model = Model([encoder_input, decoder_input], decoder_output)
    return model

In [43]:
model = build_model()
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
history = model.fit([sequences, decoder_input], decoder_target, epochs = 10,batch_size=16)

Epoch 1/10
6250/6250 [==============================] - 251s 40ms/step - loss: 2.0422 - accuracy: 0.7178
Epoch 2/10
6250/6250 [==============================] - 230s 37ms/step - loss: 1.7223 - accuracy: 0.7367
Epoch 3/10
6250/6250 [==============================] - 225s 36ms/step - loss: 1.5325 - accuracy: 0.7487
Epoch 4/10
6250/6250 [==============================] - 280s 45ms/step - loss: 1.3888 - accuracy: 0.7593
Epoch 5/10
6250/6250 [==============================] - 287s 46ms/step - loss: 1.2720 - accuracy: 0.7693
Epoch 6/10
6250/6250 [==============================] - 281s 45ms/step - loss: 1.1721 - accuracy: 0.7791
Epoch 7/10
6250/6250 [==============================] - 236s 38ms/step - loss: 1.0852 - accuracy: 0.7888
Epoch 8/10
6250/6250 [==============================] - 224s 36ms/step - loss: 1.0078 - accuracy: 0.7987
Epoch 9/10
6250/6250 [==============================] - 224s 36ms/step - loss: 0.9403 - accuracy: 0.8083
Epoch 10/10
6250/6250 [==============================] 

In [48]:
model.save("eng_hi_seq2seq.h5")


In [2]:
import tensorflow as tf

In [3]:
seq2seqModel=tf.keras.models.load_model('eng_hi_seq2seq.h5')

In [4]:
seq2seqModel.summary()


Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 30)]         0           []                               
                                                                                                  
 input_2 (InputLayer)           [(None, 39)]         0           []                               
                                                                                                  
 embedding (Embedding)          (None, 30, 128)      3840000     ['input_1[0][0]']                
                                                                                                  
 embedding_1 (Embedding)        (None, 39, 128)      3840000     ['input_2[0][0]']                
                                                                                              

In [7]:
encoder_inputs = seq2seqModel.input[0]
encoder_lstm = seq2seqModel.get_layer('lstm')

_, state_h, state_c = encoder_lstm.output
encoder_states = [state_h, state_c]

encoder_model = Model(
    encoder_inputs,
    encoder_states
)

In [8]:
encoder_model.summary()


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 30)]              0         
                                                                 
 embedding (Embedding)       (None, 30, 128)           3840000   
                                                                 
 lstm (LSTM)                 [(None, 256),             394240    
                              (None, 256),                       
                              (None, 256)]                       
                                                                 
Total params: 4,234,240
Trainable params: 4,234,240
Non-trainable params: 0
_________________________________________________________________


In [62]:
encoder_model.save("encoder_inference.h5")

In [ ]:
#decoder:


In [9]:
decoder_embedding = seq2seqModel.get_layer("embedding_1")
decoder_dense = seq2seqModel.get_layer("dense")
trained_decoder_lstm = seq2seqModel.get_layer("lstm_1")
hidden_units = trained_decoder_lstm.units


In [10]:

dummy_input = Input(shape=(1, embedding_dim))
dummy_state_h = Input(shape=(hidden_units,))
dummy_state_c = Input(shape=(hidden_units,))

decoder_lstm_inf = LSTM(
    hidden_units,
    return_sequences=True,
    return_state=True
)
decoder_lstm_inf(
    dummy_input,
    initial_state=[dummy_state_h, dummy_state_c]
)

# 2. NOW copy weights
decoder_lstm_inf.set_weights(trained_decoder_lstm.get_weights())


In [11]:
decoder_state_input_h = Input(shape=(hidden_units,))
decoder_state_input_c = Input(shape=(hidden_units,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]


In [12]:
decoder_single_input = Input(shape=(1,))
decoder_embedded = decoder_embedding(decoder_single_input)


In [13]:
decoder_outputs, state_h, state_c = decoder_lstm_inf(
    decoder_embedded,
    initial_state=decoder_states_inputs
)
decoder_states = [state_h, state_c]

In [14]:
decoder_outputs = decoder_dense(decoder_outputs)


In [15]:
decoder_model = Model(
    [decoder_single_input] + decoder_states_inputs,
    [decoder_outputs] + decoder_states
)


In [63]:
decoder_model.save("decoder_inference.h5")

In [52]:
def decode_sequence(input_seq):
    states = encoder_model.predict(input_seq)

    target_seq = np.zeros((1, 1))
    target_seq[0, 0] = tokenizer_hi.word_index['<sos>']

    decoded_sentence = []

    while True:
        output_tokens, h, c = decoder_model.predict(
            [target_seq] + states
        )

        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        if sampled_token_index == 0:
            break
        sampled_word = tokenizer_hi.index_word[sampled_token_index]

        if sampled_word == '<eos>' or len(decoded_sentence) > 39:
            break

        decoded_sentence.append(sampled_word)

        target_seq[0, 0] = sampled_token_index
        states = [h, c]

    return ' '.join(decoded_sentence)


In [53]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
def clean_sentence(s):
    s = s.lower().strip()
    s=tokenizer.texts_to_sequences([s])
    s=pad_sequences(s,maxlen=30,padding="post")
    return s


In [54]:
s="The city is a good place to live these days but a village is something even better"
cleaned_s=clean_sentence(s)

In [55]:
cleaned_s

array([[  2, 466,   8,   7, 106, 157,   5, 515,  76, 272,  37,   7, 722,
          8, 256, 123, 287,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0]])

In [211]:
decode_sequence(cleaned_s)

1/1 [==============================] - 0s 17ms/step


'अपना अपना अपना (_ अपना इस अपना थी यही अपना थी का उसका थी समय था। बात उसने का उसका उसका उसका उसका थी तुम्हें दी तुम्हें बीच उसका उसका उसका थी तुम्हें दी तुम्हें बीच उसका थी तुम्हें अब'

In [56]:
check=clean_sentence("I am happy")


In [57]:
decode_sequence(check)

1/1 [==============================] - 0s 51ms/step


'मुझे प्रसन्नता है'

In [59]:
decode_sequence(clean_sentence("He is a boy"))



1/1 [==============================] - 0s 33ms/step


'वह एक <OOV> है.'

In [60]:

decode_sequence(clean_sentence("She is my friend"))

1/1 [==============================] - 0s 28ms/step


'मेरा और मेरे साथियों को'

In [61]:
tests = [
    "I am happy",
    "He is here",
    "She is fine",
    "This is a book",
    "I need help"
]

for t in tests:
    print(t, "→", decode_sequence(clean_sentence(t)))


1/1 [==============================] - 0s 38ms/step
I am happy → मुझे प्रसन्नता है
1/1 [==============================] - 0s 35ms/step
He is here → वह <OOV>
1/1 [==============================] - 0s 54ms/step
She is fine → वह <OOV> <OOV> है।
1/1 [==============================] - 0s 33ms/step
This is a book → यह एक किताब है
1/1 [==============================] - 0s 69ms/step
I need help → मैं काम करने के लिए मदद कर सकता/सकती हूँ?
