In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [6]:
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000,n_features=10,n_classes=3,random_state=42,n_informative=3)
x=pd.DataFrame(x)
y=pd.DataFrame(y)

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [9]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()
logistic.fit(x_train,y_train)
y_pred=logistic.predict(x_test)

c:\Users\vatsa\Downloads\KrishNaikML\venv\lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
score=accuracy_score(y_pred,y_test)
print(score)
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.7033333333333334
              precision    recall  f1-score   support

           0       0.74      0.74      0.74       103
           1       0.50      0.60      0.55        80
           2       0.86      0.74      0.80       117

    accuracy                           0.70       300
   macro avg       0.70      0.69      0.69       300
weighted avg       0.72      0.70      0.71       300

[[76 25  2]
 [20 48 12]
 [ 7 23 87]]
